### ISSUE TITLE
Broken test: ResponseFormats_IISExpress_Chunked

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/ServerTests#114]
This test [fails](http://aspnetci/viewLog.html?buildId=457039&buildTypeId=Releases_21Public_Win2012) with the following error:
```
/chunked, chunked?
Expected: True
Actual:   (null)
   at ServerComparison.FunctionalTests.ResponseTests.CheckChunkedAsync(HttpClient client, ILogger logger) in /_/test/ServerComparison.FunctionalTests/ResponseTests.cs:line 349
   at ServerComparison.FunctionalTests.ResponseTests.ResponseFormats(ServerType serverType, RuntimeFlavor runtimeFlavor, RuntimeArchitecture architecture, Func`3 scenario, ApplicationType applicationType, String testName, HostingModel hostingModel, String additionalPublishParameters) in /_/test/ServerComparison.FunctionalTests/ResponseTests.cs:line 261
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [2018-04-27T10:28:39] TestLifetime Information: Starting test ResponseFormats_IISExpress_Chunked-CoreClr-Standalone-InProcess- /p:ANCMVersion=V2
| [2018-04-27T10:28:39] TestLifetime Information: Starting test ResponseFormats_IISExpress_Chunked_IISExpress_CoreClr_x64_Standalone
| [2018-04-27T10:28:39] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: Deploying [Variation] :: ServerType=IISExpress, Runtime=CoreClr, Arch=x64, BaseUrlHint=, Publish=False
| [2018-04-27T10:28:39] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: SET ASPNETCORE_ENVIRONMENT=Responses
| [2018-04-27T10:28:39] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: Executing command dotnet publish  --output "C:\b\t\buildTmp\2f684a70-08e5-4c3f-a774-9d4a1080da30" --framework netcoreapp2.1 --configuration Debug --no-restore -p:VerifyMatchingImplicitPackageVersion=false --runtime win7-x64  /p:ANCMVersion=V2
| [2018-04-27T10:28:39] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: dotnet-publish stdout: Microsoft (R) Build Engine version 15.7.145.53551 for .NET Core
| [2018-04-27T10:28:39] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: dotnet-publish stdout: Copyright (C) Microsoft Corporation. All rights reserved.
| [2018-04-27T10:28:40] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: dotnet-publish stdout:   ServerComparison.TestSites -> C:\b\w\33bdfc1cae7b2a38\modules\ServerTests\test\ServerComparison.TestSites\bin\Debug\netcoreapp2.1\win7-x64\ServerComparison.TestSites.dll
| [2018-04-27T10:28:41] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: dotnet-publish stdout:   ServerComparison.TestSites -> C:\b\t\buildTmp\2f684a70-08e5-4c3f-a774-9d4a1080da30\
| [2018-04-27T10:28:41] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: dotnet publish finished with exit code : 0
| [2018-04-27T10:28:41] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: Attempting to start IIS Express on port: 57629
| [2018-04-27T10:28:41] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: Executing command : C:\Program Files\IIS Express\iisexpress.exe /site:HttpTestSite /config:C:\b\t\buildTmp\tmp8A18.tmp /trace:error
| [2018-04-27T10:28:41] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: SET ASPNETCORE_ENVIRONMENT=Responses
| [2018-04-27T10:28:41] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: SET ASPNETCORE_DETAILEDERRORS=true
| [2018-04-27T10:28:41] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress Process 7124 started
| [2018-04-27T10:28:41] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: Starting IIS Express ...
| [2018-04-27T10:28:41] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: Initializing the W3 Server Started CTC = 1297320515 
| [2018-04-27T10:28:41] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: W3 Server initializing WinSock.  CTC = 1297320515 
| [2018-04-27T10:28:41] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: W3 Server WinSock initialized.  CTC = 1297320515 
| [2018-04-27T10:28:41] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: W3 Server ThreadPool initialized (ipm has signalled).  CTC = 1297320515 
| [2018-04-27T10:28:41] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: Start listenerChannel http:0
| [2018-04-27T10:28:41] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: Successfully registered URL "http://localhost:57629/" for site "HttpTestSite" application "/"
| [2018-04-27T10:28:41] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: Registration completed for site "HttpTestSite"
| [2018-04-27T10:28:41] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: AppPool 'IISExpressAppPool' initialized
| [2018-04-27T10:28:41] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: InitComplete event signalled
| [2018-04-27T10:28:41] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: IIS Express is running.
| [2018-04-27T10:28:41] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: Started iisexpress successfully. Process Id : 7124, Port: 57629
| [2018-04-27T10:28:41] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: Application ready at URL: http://localhost:57629/
| [2018-04-27T10:28:41] ResponseFormats Warning: Retry count 1..
| [2018-04-27T10:28:41] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: IncrementMessages called
| [2018-04-27T10:28:41] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: Request started: "GET" http://localhost:57629/
| [2018-04-27T10:28:41] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: Hosting environment: Responses
| [2018-04-27T10:28:41] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: Content root path: C:\b\t\buildTmp\2f684a70-08e5-4c3f-a774-9d4a1080da30\
| [2018-04-27T10:28:41] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: Application started. Press Ctrl+C to shut down.
| [2018-04-27T10:28:41] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
| [2018-04-27T10:28:41] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout:       Request starting HTTP/1.1 GET http://localhost:57629/  
| [2018-04-27T10:28:42] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
| [2018-04-27T10:28:42] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout:       Request finished in 80.6537ms 200 
| [2018-04-27T10:28:42] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: Request ended: http://localhost:57629/ with HTTP status 200.0
| [2018-04-27T10:28:42] ResponseFormats Information: Testing Chunked
| [2018-04-27T10:28:42] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: IncrementMessages called
| [2018-04-27T10:28:42] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: Request started: "GET" http://localhost:57629/chunked
| [2018-04-27T10:28:42] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
| [2018-04-27T10:28:42] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout:       Request starting HTTP/1.1 GET http://localhost:57629/chunked  
| [2018-04-27T10:28:42] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
| [2018-04-27T10:28:42] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout:       Request finished in 3.1811ms 200 
| [2018-04-27T10:28:42] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: Request ended: http://localhost:57629/chunked with HTTP status 200.0
| [2018-04-27T10:28:42] ResponseFormats Warning: StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.HttpConnection+HttpConnectionResponseContent, Headers:
|                                                {
|                                                  Server: Microsoft-IIS/10.0
|                                                  X-SourceFiles: =?UTF-8?B?QzpcYlx0XGJ1aWxkVG1wXDJmNjg0YTcwLTA4ZTUtNGMzZi1hNzc0LTlkNGExMDgwZGEzMFxjaHVua2Vk?=
|                                                  X-Powered-By: ASP.NET
|                                                  Date: Fri, 27 Apr 2018 17:28:42 GMT
|                                                  Content-Length: 7
|                                                }
| [2018-04-27T10:28:42] ResponseFormats Warning: Chunked
| [2018-04-27T10:28:42] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: Attempting to cancel process 7124
| [2018-04-27T10:28:42] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress Process 7124 shut down
| [2018-04-27T10:28:42] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: Host process shutting down.
| [2018-04-27T10:28:42] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: Successfully terminated host process with process Id '7124'
| [2018-04-27T10:28:42] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: [Time]: Total time taken for this test variation '3.4894237' seconds
| [2018-04-27T10:28:42] TestLifetime Information: Finished test ResponseFormats_IISExpress_Chunked_IISExpress_CoreClr_x64_Standalone in 3.4904044s
```

**Comment by Tratcher** [comment]
This was disabled in dev but is still failing in release. https://github.com/aspnet/ServerTests/issues/110

**Comment by Tratcher** [comment]
Disabled in release.
