### ISSUE TITLE
FlakyTest: SmokeTests.Smoke_Tests(variant: Server: IISExpress, TFM: netcoreapp2.1, Type: Portable, Arch: x64, ANCM: V2, Host: InProcess) 

### ISSUE THREAD

**Issue by jkotalik** [aspnet/ServerTests#130]
```
Assert.Equal() Failure
Expected: OK
Actual:   InternalServerError
   at E2ETests.Validator.VerifyHomePage(HttpResponseMessage response, Boolean useNtlmAuthentication) in C:\BuildAgent\work\33bdfc1cae7b2a38\modules\MusicStore\test\MusicStore.E2ETests\Implementation\Validator.cs:line 94
   at E2ETests.SmokeTests.RunTestsAsync(DeploymentResult deploymentResult, ILogger logger) in C:\BuildAgent\work\33bdfc1cae7b2a38\modules\MusicStore\test\MusicStore.E2ETests\SmokeTests.cs:line 82
   at E2ETests.SmokeTests.Smoke_Tests(TestVariant variant) in C:\BuildAgent\work\33bdfc1cae7b2a38\modules\MusicStore\test\MusicStore.E2ETests\SmokeTests.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [0.001s] TestLifetime Information: Starting test Smoke_Tests-Server: IISExpress, TFM: netcoreapp2.1, Type: Portable, Arch: x64, ANCM: V2, Host: InProcess at 2018-07-02T20:45:14
| [0.001s] TestLifetime Information: Starting test SmokeTestSuite_Server: IISExpress, TFM: netcoreapp2.1, Type: Portable, Arch: x64, ANCM: V2, Host: InProcess at 2018-07-02T20:45:14
| [0.002s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: Deploying [Variation] :: ServerType=IISExpress, Runtime=CoreClr, Arch=x64, BaseUrlHint=, Publish=False
| [0.002s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: Executing: dotnet C:\BuildAgent\work\33bdfc1cae7b2a38\modules\MusicStore\samples\MusicStore\bin\Release\netcoreapp2.1\MusicStore.dll
| [0.002s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: ContentRoot: C:\BuildAgent\work\33bdfc1cae7b2a38\modules\MusicStore\samples\MusicStore
| [0.002s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: Attempting to start IIS Express on port: 62140
| [0.005s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: Executing command : C:\Program Files\IIS Express\iisexpress.exe /site:HttpTestSite /config:C:\BuildAgent\temp\buildTmp\tmp40AE.tmp /trace:error
| [0.005s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: SET ASPNETCORE_ENVIRONMENT=SocialTesting
| [0.005s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: SET ASPNETCORE_DETAILEDERRORS=true
| [0.005s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: SET Data__DefaultConnection__ConnectionString=Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=MusicStore_Test_d4efc2b26fc84b578f7e914fc93cf8c0;Integrated Security=True;MultipleActiveResultSets=True;Connect Timeout=30
| [0.005s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: SET LAUNCHER_PATH=dotnet
| [0.005s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: SET LAUNCHER_ARGS=C:\BuildAgent\work\33bdfc1cae7b2a38\modules\MusicStore\samples\MusicStore\bin\Release\netcoreapp2.1\MusicStore.dll
| [0.005s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: SET ASPNETCORE_CONTENTROOT=C:\BuildAgent\work\33bdfc1cae7b2a38\modules\MusicStore\samples\MusicStore
| [0.007s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress Process 10916 started
| [0.054s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: Starting IIS Express ...
| [0.068s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: Initializing the W3 Server Started CTC = 1597194421 
| [0.073s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: W3 Server initializing WinSock.  CTC = 1597194437 
| [0.073s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: W3 Server WinSock initialized.  CTC = 1597194437 
| [0.073s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: W3 Server ThreadPool initialized (ipm has signalled).  CTC = 1597194437 
| [0.091s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: Start listenerChannel http:0
| [0.092s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: Successfully registered URL "http://localhost:62140/" for site "HttpTestSite" application "/"
| [0.092s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: Registration completed for site "HttpTestSite"
| [0.092s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: AppPool 'IISExpressAppPool' initialized
| [0.092s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: InitComplete event signalled
| [0.092s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: IIS Express is running.
| [0.093s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: Started iisexpress successfully. Process Id : 10916, Port: 62140
| [0.093s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: Application ready at URL: http://localhost:62140/
| [0.093s] SmokeTestSuite Warning: Retry count 1..
| [11.077s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: IncrementMessages called
| [11.079s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: Request started: "GET" http://localhost:62140/
| [15.016s] System.Net.Http.HttpClient Error: Exception while sending 'GET http://localhost:62140/' : System.Threading.Tasks.TaskCanceledException: The operation was canceled. ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request.. ---> System.Net.Sockets.SocketException: The I/O operation has been aborted because of either a thread exit or an application request.
|                                                --- End of inner exception stack trace ---
|                                                at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
|                                                at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
|                                                at System.Net.Http.HttpConnection.FillAsync()
|                                                at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
|                                                at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
|                                                --- End of inner exception stack trace ---
|                                                at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
|                                                at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
|                                                at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
|                                                at Microsoft.AspNetCore.Server.IntegrationTesting.LoggingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
| System.Threading.Tasks.TaskCanceledException: The operation was canceled. ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request.. ---> System.Net.Sockets.SocketException: The I/O operation has been aborted because of either a thread exit or an application request.
|    --- End of inner exception stack trace ---
|    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
|    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
|    at System.Net.Http.HttpConnection.FillAsync()
|    at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
|    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
|    --- End of inner exception stack trace ---
|    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
|    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
|    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
|    at Microsoft.AspNetCore.Server.IntegrationTesting.LoggingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
| [15.042s] SmokeTestSuite Warning: Retry count 2..
| [15.043s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: IncrementMessages called
| [15.043s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: Request started: "GET" http://localhost:62140/
| [18.202s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: [aspnetcore.dll] Failed HRESULT returned: 0x8027025b at c:\b\w\33bdfc1cae7b2a38\modules\iisintegration\src\aspnetcoremodulev2\aspnetcore\src\applicationinfo.cpp:192 
| [18.203s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: Request ended: http://localhost:62140/ with HTTP status 500.0
| [18.204s] SmokeTestSuite Information: Verifying home page
| [18.205s] SmokeTestSuite Information: Home page content : <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head> 
<title>IIS 10.0 Detailed Error - 500.0 - Internal Server Error</title> 
<style type="text/css"> 
<!-- 
body{margin:0;font-size:.7em;font-family:Verdana,Arial,Helvetica,sans-serif;} 
code{margin:0;color:#006600;font-size:1.1em;font-weight:bold;} 
.config_source code{font-size:.8em;color:#000000;} 
pre{margin:0;font-size:1.4em;word-wrap:break-word;} 
ul,ol{margin:10px 0 10px 5px;} 
ul.first,ol.first{margin-top:5px;} 
fieldset{padding:0 15px 10px 15px;word-break:break-all;} 
.summary-container fieldset{padding-bottom:5px;margin-top:4px;} 
legend.no-expand-all{padding:2px 15px 4px 10px;margin:0 0 0 -12px;} 
legend{color:#333333;;margin:4px 0 8px -12px;_margin-top:0px; 
font-weight:bold;font-size:1em;} 
a:link,a:visited{color:#007EFF;font-weight:bold;} 
a:hover{text-decoration:none;} 
h1{font-size:2.4em;margin:0;color:#FFF;} 
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.4em;margin:10px 0 0 0;color:#CC0000;} 
h4{font-size:1.2em;margin:10px 0 5px 0; 
}#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS",Verdana,sans-serif; 
 color:#FFF;background-color:#5C87B2; 
}#content{margin:0 0 0 2%;position:relative;} 
.summary-container,.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;} 
.content-container p{margin:0 0 10px 0; 
}#details-left{width:35%;float:left;margin-right:2%; 
}#details-right{width:63%;float:left;overflow:hidden; 
}#server_version{width:96%;_height:1px;min-height:1px;margin:0 0 5px 0;padding:11px 2% 8px 2%;color:#FFFFFF; 
 background-color:#5A7FA5;border-bottom:1px solid #C1CFDD;border-top:1px solid #4A6C8E;font-weight:normal; 
 font-size:1em;color:#FFF;text-align:right; 
}#server_version p{margin:5px 0;} 
table{margin:4px 0 4px 0;width:100%;border:none;} 
td,th{vertical-align:top;padding:3px 0;text-align:left;font-weight:normal;border:none;} 
th{width:30%;text-align:right;padding-right:2%;font-weight:bold;} 
thead th{background-color:#ebebeb;width:25%; 
}#details-right th{width:20%;} 
table tr.alt td,table tr.alt th{} 
.highlight-code{color:#CC0000;font-weight:bold;font-style:italic;} 
.clear{clear:both;} 
.preferred{padding:0 5px 2px 5px;font-weight:normal;background:#006633;color:#FFF;font-size:.8em;} 
--> 
</style> 
 
</head> 
<body> 
<div id="content"> 
<div class="content-container"> 
  <h3>HTTP Error 500.0 - Internal Server Error</h3> 
  <h4>The page cannot be displayed because an internal server error has occurred.</h4> 
</div> 
<div class="content-container"> 
 <fieldset><h4>Most likely causes:</h4> 
  <ul>     <li>IIS received the request; however, an internal error occurred during the processing of the request. The root cause of this error depends on which module handles the request and what was happening in the worker process when this error occurred.</li>     <li>IIS was not able to access the web.config file for the Web site or application. This can occur if the NTFS permissions are set incorrectly.</li>     <li>IIS was not able to process configuration for the Web site or application.</li>     <li>The authenticated user does not have permission to use this DLL.</li>     <li>The request is mapped to a managed handler but the .NET Extensibility Feature is not installed.</li> </ul> 
 </fieldset> 
</div> 
<div class="content-container"> 
 <fieldset><h4>Things you can try:</h4> 
  <ul>     <li>Ensure that the NTFS permissions for the web.config file are correct and allow access to the Web server's machine account.</li>     <li>Check the event logs to see if any additional information was logged.</li>     <li>Verify the permissions for the DLL.</li>     <li>Install the .NET Extensibility feature if the request is mapped to a managed handler.</li>     <li>Check the failed request tracing logs for additional information about this error. For more information, click <a href="http://go.microsoft.com/fwlink/?LinkID=66439">here</a>. </li> </ul> 
 </fieldset> 
</div> 
 
<div class="content-container"> 
 <fieldset><h4>Detailed Error Information:</h4> 
  <div id="details-left"> 
   <table border="0" cellpadding="0" cellspacing="0"> 
    <tr class="alt"><th>Module</th><td>&nbsp;&nbsp;&nbsp;AspNetCoreModuleV2</td></tr> 
    <tr><th>Notification</th><td>&nbsp;&nbsp;&nbsp;ExecuteRequestHandler</td></tr> 
    <tr class="alt"><th>Handler</th><td>&nbsp;&nbsp;&nbsp;aspNetCore</td></tr> 
    <tr><th>Error Code</th><td>&nbsp;&nbsp;&nbsp;0x8027025b</td></tr> 
     
   </table> 
  </div> 
  <div id="details-right"> 
   <table border="0" cellpadding="0" cellspacing="0"> 
    <tr class="alt"><th>Requested URL</th><td>&nbsp;&nbsp;&nbsp;http://localhost:62140/</td></tr> 
    <tr><th>Physical Path</th><td>&nbsp;&nbsp;&nbsp;C:\BuildAgent\work\33bdfc1cae7b2a38\modules\MusicStore\samples\MusicStore</td></tr> 
    <tr class="alt"><th>Logon Method</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr> 
    <tr><th>Logon User</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr> 
    <tr class="alt"><th>Request Tracing Directory</th><td>&nbsp;&nbsp;&nbsp;C:\Users\asplab\Documents\IISExpress\TraceLogFiles\HTTPTESTSITE</td></tr> 
   </table> 
   <div class="clear"></div> 
  </div> 
 </fieldset> 
</div> 
 
<div class="content-container"> 
 <fieldset><h4>More Information:</h4> 
  This error means that there was a problem while processing the request. The request was received by the Web server, but during processing a fatal error occurred, causing the 500 error. 
  <p><a href="https://go.microsoft.com/fwlink/?LinkID=62293&amp;IIS70Error=500,0,0x8027025b,7601">View more information &raquo;</a></p> 
  <p>Microsoft Knowledge Base Articles:</p> 
 <ul><li>294807</li></ul> 
 
 </fieldset> 
</div> 
</div> 
</body> 
</html> 

| [18.209s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: Attempting to cancel process 10916
| [18.281s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress Process 10916 shut down
| [18.281s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: Host process shutting down.
| [18.281s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: Successfully terminated host process with process Id '10916'
| [18.282s] SmokeTestSuite Information: Trying to drop database 'MusicStore_Test_d4efc2b26fc84b578f7e914fc93cf8c0'
| [18.352s] SmokeTestSuite Information: Successfully dropped database MusicStore_Test_d4efc2b26fc84b578f7e914fc93cf8c0
| [18.352s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: [Time]: Total time taken for this test variation '18.3736819' seconds
| [18.352s] TestLifetime Information: Finished test SmokeTestSuite_Server: IISExpress, TFM: netcoreapp2.1, Type: Portable, Arch: x64, ANCM: V2, Host: InProcess in 18.3743463s
| [18.355s] TestLifetime Information: Finished test Smoke_Tests-Server: IISExpress, TFM: netcoreapp2.1, Type: Portable, Arch: x64, ANCM: V2, Host: InProcess in 18.376765s
```

**Comment by Tratcher** [comment]
Shouldn't this be in MusicStore?
