### ISSUE TITLE
Test failure: ResponseCompression_AppAndHostCompression

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/ServerTests#140]
This test [fails](http://aspnetci/viewLog.html?buildId=529245&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR) occasionally with the following error:
```
System.InvalidOperationException : Failed to start nginx
   at Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer.SetupNginx(String redirectUri, Uri originalUri)
   at Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer.DeployAsync()
   at ServerComparison.FunctionalTests.ResponseCompressionTests.ResponseCompression(TestVariant variant, Func`3 scenario, Boolean hostCompression, String testName) in /_/test/ServerComparison.FunctionalTests/ResponseCompressionTests.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [0.000s] TestLifetime Information: Starting test ResponseCompression_AppAndHostCompression-Server: Nginx, TFM: netcoreapp2.2, Type: Portable, Arch: x64 at 2018-08-11T22:01:10
| [0.000s] TestLifetime Information: Starting test ResponseCompression_AppAndHostCompression_Nginx_netcoreapp2.2_x64_Portable at 2018-08-11T22:01:10
| [0.001s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Information: Executing dotnet /mnt/work/33bdfc1cae7b2a38/modules/ServerTests/test/ServerComparison.TestSites/bin/Release/netcoreapp2.2/ServerComparison.TestSites.dll --urls http://localhost:36893/ --server Microsoft.AspNetCore.Server.Kestrel
| [0.001s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Information: SET ASPNETCORE_ENVIRONMENT=ResponseCompression
| [0.001s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Information: SET ASPNETCORE_DETAILEDERRORS=true
| [0.001s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Information: SET ASPNETCORE_CONTENTROOT=/mnt/work/33bdfc1cae7b2a38/modules/ServerTests/test/ServerComparison.TestSites
| [0.004s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Information: Started dotnet. Process Id : 11216
| [0.904s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: host process ID 11190 shut down
| [0.904s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Host process shutting down.
| [0.432s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Information: dotnet stdout: Hosting environment: ResponseCompression
| [0.433s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Information: dotnet stdout: Content root path: /mnt/work/33bdfc1cae7b2a38/modules/ServerTests/test/ServerComparison.TestSites
| [0.433s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Information: dotnet stdout: Now listening on: http://localhost:36893
| [0.433s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Information: dotnet stdout: Application started. Press Ctrl+C to shut down.
| [0.439s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Warning: nginx start stderr: nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
| [0.443s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Warning: nginx start stderr: nginx: [emerg] bind() to 0.0.0.0:45443 failed (98: Address already in use)
| [0.443s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Warning: nginx start stderr: nginx: [emerg] bind() to 0.0.0.0:45443 failed (98: Address already in use)
| [0.443s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Warning: nginx start stderr: nginx: [emerg] bind() to 0.0.0.0:45443 failed (98: Address already in use)
| [0.443s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Warning: nginx start stderr: nginx: [emerg] bind() to 0.0.0.0:45443 failed (98: Address already in use)
| [0.943s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Warning: nginx start stderr: nginx: [emerg] bind() to 0.0.0.0:45443 failed (98: Address already in use)
| [0.943s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Warning: nginx start stderr: nginx: [emerg] bind() to 0.0.0.0:45443 failed (98: Address already in use)
| [0.943s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Warning: nginx start stderr: nginx: [emerg] bind() to 0.0.0.0:45443 failed (98: Address already in use)
| [0.943s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Warning: nginx start stderr: nginx: [emerg] bind() to 0.0.0.0:45443 failed (98: Address already in use)
| [1.443s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Warning: nginx start stderr: nginx: [emerg] bind() to 0.0.0.0:45443 failed (98: Address already in use)
| [1.443s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Warning: nginx start stderr: nginx: [emerg] bind() to 0.0.0.0:45443 failed (98: Address already in use)
| [1.443s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Warning: nginx start stderr: nginx: [emerg] bind() to 0.0.0.0:45443 failed (98: Address already in use)
| [1.444s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Warning: nginx start stderr: nginx: [emerg] bind() to 0.0.0.0:45443 failed (98: Address already in use)
| [1.943s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Warning: nginx start stderr: nginx: [emerg] bind() to 0.0.0.0:45443 failed (98: Address already in use)
| [1.944s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Warning: nginx start stderr: nginx: [emerg] bind() to 0.0.0.0:45443 failed (98: Address already in use)
| [1.944s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Warning: nginx start stderr: nginx: [emerg] bind() to 0.0.0.0:45443 failed (98: Address already in use)
| [1.944s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Warning: nginx start stderr: nginx: [emerg] bind() to 0.0.0.0:45443 failed (98: Address already in use)
| [2.443s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Warning: nginx start stderr: nginx: [emerg] bind() to 0.0.0.0:45443 failed (98: Address already in use)
| [2.444s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Warning: nginx start 
...
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on master.

CC @Eilon (because the bot doesn't know who else to pick)

This issue was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by Tratcher** [comment]
Hmm, https://github.com/aspnet/ServerTests/issues/135#issuecomment-411896633 should have addressed this. Need to verify it had that change in this build.
