### ISSUE TITLE
1.1.3 Test failure on Ubuntu

### ISSUE THREAD

**Issue by pranavkm** [aspnet/ServerTests#72]
```
System.Exception : Failed to start Nginx
   at Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer.SetupNginx(String redirectUri, Uri originalUri)
   at Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer.Deploy()
   at ServerComparison.FunctionalTests.ResponseTests.<ResponseFormats>d__15.MoveNext() in /datadrive/d6337ac2abf63a4b/.repositories/ServerTests/test/ServerComparison.FunctionalTests/ResponseTests.cs:line 176
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by pranavkm** [comment]
cc @Tratcher \ @muratg \ @Eilon

**Comment by Tratcher** [comment]
@anurse @BrennanConroy

**Comment by Eilon** [comment]
@muratg - can you assign?

**Comment by JunTaoLuo** [comment]
Something on the agent is listening on the port
```
tcp        0      0 0.0.0.0:5094            0.0.0.0:*               LISTEN      38327/tmpOQZvkC.tmp
```

**Comment by JunTaoLuo** [comment]
Looks like it's a previous nginx run that did not clean up.

**Comment by JunTaoLuo** [comment]
Rebooting machine, this should be solved after this.
