### ISSUE TITLE
Failure: ResponseTests.ResponseFormats_Kestrel_Http10ConnectionClose

### ISSUE THREAD

**Issue by Tratcher** [aspnet/ServerTests#74]
```
System.Exception : Command exited unexpectedly with exit code: 134
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Testing.TaskExtensions.<TimeoutAfter>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer.<StartSelfHostAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer.<DeployAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ServerComparison.FunctionalTests.ResponseTests.<ResponseFormats>d__16.MoveNext()
```

http://aspnetci/viewLog.html?buildId=203900&tab=buildResultsDiv&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR

**Comment by muratg** [comment]
Fixed, or is it disabled?

**Comment by Tratcher** [comment]
Recent failures can be attributed to overall build instability rather than any specific issues with these tests. E.g. breaking changes in Kestrel dependencies.
