### ISSUE TITLE
[Patch 1.1.3][Flaky test]: ServerComparison.FunctionalTests.dll (1…untimeFlavor: CoreClr, architecture: x64, applicationBaseUrl on Ubuntu

### ISSUE THREAD

**Issue by pranavkm** [aspnet/ServerTests#78]
```
System.AggregateException : One or more errors occurred. (A task was canceled.)
---- System.Threading.Tasks.TaskCanceledException : A task was canceled.
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer.Deploy()
   at ServerComparison.FunctionalTests.ResponseTests.<ResponseFormats>d__15.MoveNext() in /datadrive/d6337ac2abf63a4b/.repositories/ServerTests/test/ServerComparison.FunctionalTests/ResponseTests.cs:line 176
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----
```

**Comment by pranavkm** [comment]
cc @Tratcher \ @Eilon

**Comment by Eilon** [comment]
@Tratcher - can you investigate this flakiness in the 1.1.3 patch build?

**Comment by Eilon** [comment]
(And perhaps this is also an issue in `dev` as well.)

**Comment by Eilon** [comment]
cc @muratg

**Comment by muratg** [comment]
@Tratcher good to close?

**Comment by Tratcher** [comment]
No failures in recorded build history, the prior history may have been deleted. Closing as no-repro.
